### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by BhuvanGarla** [Dhruv-Limbachiya/ShopKart#1]
How change data in Firebase

**Comment by DhruvLimbachiya** [comment]
There are two ways to change data in Firebase
1. Programmatically - https://firebase.google.com/docs/database/android/read-and-write#update_specific_fields 
2. Firebase Console

**Comment by BhuvanGarla** [comment]
How can I change those images of products in dashboard .
Please help

**Comment by BhuvanGarla** [comment]
Can I open your firebase or I have to create and add my data

**Comment by BhuvanGarla** [comment]
Your phone number

**Comment by Dhruv-Limbachiya** [comment]
You have to create your own firebase project and add data accordingly.

**Comment by Kkm12** [comment]
> How change data in Firebase

Can You Solve It?

**Comment by Dhruv-Limbachiya** [comment]
I can. I need you to solve this issue.  You can refer Firebase doc to solve issues

**Comment by Kkm12** [comment]
How can you help me
